import { Building2, CircleDollarSign, Layers3, Users, Wrench } from 'lucide-react'
import { useState } from 'react'
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { KpiCard } from '../components/KpiCard'
import { Panel } from '../components/Panel'
import { companies, deals } from '../data/mockData'
import { useFilters } from '../context/FilterContext'
import { filterDeals, formatCurrency, formatNumber, formatPercent, sumBy } from '../utils/calculations'
import type { CompanyId } from '../types'

const palette = ['#0ea5e9', '#38bdf8', '#7dd3fc', '#bae6fd', '#0369a1']

function MontseguroView() {
  const { filters } = useFilters()
  const scoped = filterDeals(deals, { ...filters, companyId: 'montseguro' })
  const implemented = scoped.filter((deal) => deal.implementationStatus === 'completed' || deal.implementationStatus === 'pending')
  const lives = sumBy(implemented, (deal) => deal.lives)
  const operatorData = Object.entries(implemented.reduce<Record<string, number>>((result, deal) => ({ ...result, [deal.operator ?? 'Outras']: (result[deal.operator ?? 'Outras'] ?? 0) + (deal.lives ?? 0) }), {})).map(([name, value]) => ({ name, value }))
  const contracted = 51
  const implementationLoss = 1 - 42 / contracted
  const avgPerLife = lives ? sumBy(implemented, (deal) => deal.amount) / lives / 12 : 0
  return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="Vidas cobertas" value={formatNumber(lives)} meta={`${implemented.length} grupos em implantação/ativos`} change={0.09} description="Vidas elegíveis em contratos ativos ou em implantação." tone="accent" /><KpiCard label="Ticket por vida" value={formatCurrency(avgPerLife)} meta="mensal estimado" change={0.04} description="Prêmio anual contratado dividido por vidas e por 12 meses." /><KpiCard label="Quebra na implantação" value={formatPercent(implementationLoss)} meta={`${contracted - 42} grupos não implantados`} change={-0.03} description="Perda entre contratação e implantação concluída." /><KpiCard label="Implantações pendentes" value={formatNumber(implemented.filter((deal) => deal.implementationStatus === 'pending').length)} meta="prioridade de pós-venda" change={0.12} description="Contratos que ainda não viraram base ativa." /></div><div className="grid gap-6 xl:grid-cols-[1fr_1.3fr]"><Panel title="Distribuição por operadora" subtitle="Vidas nas operações em curso"><div className="h-72"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={operatorData} dataKey="value" nameKey="name" outerRadius={90} innerRadius={54} paddingAngle={4}>{operatorData.map((entry, index) => <Cell key={entry.name} fill={palette[index % palette.length]} />)}</Pie><Tooltip formatter={(value) => [`${formatNumber(Number(value))} vidas`, 'Cobertura']} /></PieChart></ResponsiveContainer></div><div className="grid grid-cols-2 gap-2 text-sm">{operatorData.map((item, index) => <div key={item.name} className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2"><span className="flex items-center gap-2 text-slate-600"><i className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: palette[index % palette.length] }} />{item.name}</span><strong>{formatNumber(item.value)}</strong></div>)}</div></Panel><Panel title="Pós-venda e implantação" subtitle="Contratação não equivale a uma vida ativa"><div className="space-y-5"><div className="rounded-xl border border-sky-100 bg-sky-50 p-5"><div className="flex items-center gap-3"><Wrench className="text-sky-700" /><div><p className="font-bold text-sky-950">{formatNumber(contracted)} contratos contratados</p><p className="text-sm text-sky-800">Somente {formatNumber(42)} passaram por implantação concluída.</p></div></div><div className="mt-4 h-3 overflow-hidden rounded-full bg-sky-100"><div className="h-full rounded-full bg-sky-600" style={{ width: `${(42 / contracted) * 100}%` }} /></div></div><div className="rounded-xl border border-amber-100 bg-amber-50 p-4 text-sm leading-6 text-amber-900"><strong>Ação recomendada:</strong> acompanhamento semanal das pendências documentais, elegibilidade e movimentação cadastral para preservar a receita ativa.</div></div></Panel></div></div>
}

function Prop5View() {
  const { filters } = useFilters()
  const scoped = filterDeals(deals, { ...filters, companyId: 'prop5' })
  const vgv = sumBy(scoped, (deal) => deal.propertyValue)
  const commission = sumBy(scoped, (deal) => deal.actualRevenue)
  const ticket = vgv / Math.max(scoped.length, 1)
  const countries = Object.entries(scoped.reduce<Record<string, number>>((result, deal) => ({ ...result, [deal.country ?? 'Outros']: (result[deal.country ?? 'Outros'] ?? 0) + 1 }), {})).map(([country, leads]) => ({ country, leads }))
  return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="Volume transacionado" value={formatCurrency(vgv, true)} meta="VGV / volume estruturado" change={0.18} description="Volume imobiliário movimentado — não é faturamento." tone="accent" /><KpiCard label="Receita real de comissão" value={formatCurrency(commission, true)} meta={`${formatPercent(commission / Math.max(vgv, 1))} do volume`} change={0.11} description="Comissão efetivamente reconhecida pela Prop5." /><KpiCard label="Ticket médio estruturado" value={formatCurrency(ticket, true)} meta={`${scoped.length} estruturas`} change={0.06} description="Valor médio dos imóveis e estruturas em consultoria." /><KpiCard label="Ciclo consultivo" value={`${Math.round(sumBy(scoped, (deal) => deal.cycleDays) / Math.max(scoped.length, 1))} dias`} meta="da origem ao fechamento" change={-0.05} description="Tempo de maturação característico do Método M5." /></div><div className="grid gap-6 xl:grid-cols-[1.25fr_1fr]"><Panel title="Volume movimentado ≠ receita" subtitle="Separação crítica para leitura financeira correta"><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={[{ name: 'Prop5', volume: vgv, commission }]}><CartesianGrid vertical={false} stroke="#e2e8f0" /><XAxis dataKey="name" tickLine={false} axisLine={false} /><YAxis tickFormatter={(value) => formatCurrency(value, true)} tickLine={false} axisLine={false} width={66} /><Tooltip formatter={(value, name) => [formatCurrency(Number(value)), name === 'volume' ? 'Volume transacionado' : 'Receita de comissão']} /><Bar dataKey="volume" fill="#c4b5fd" radius={[8, 8, 0, 0]} /><Bar dataKey="commission" fill="#8b5cf6" radius={[8, 8, 0, 0]} /></BarChart></ResponsiveContainer></div><p className="rounded-lg bg-violet-50 px-3 py-2 text-sm text-violet-900">O VGV mostra escala de consultoria; a comissão é a receita da Prop5.</p></Panel><Panel title="Origem dos expatriados" subtitle="Países dos clientes em estruturação"><div className="space-y-3">{countries.map((item, index) => <div key={item.country} className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-violet-50 font-bold text-violet-700">{index + 1}</span><div className="flex-1"><div className="flex justify-between text-sm"><span className="font-medium text-slate-700">{item.country}</span><strong>{item.leads}</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-violet-500" style={{ width: `${(item.leads / Math.max(...countries.map((country) => country.leads), 1)) * 100}%` }} /></div></div></div>)}</div></Panel></div></div>
}

function TechBraboView() {
  const { filters } = useFilters()
  const scoped = filterDeals(deals, { ...filters, companyId: 'techbrabo' })
  const projectRevenue = sumBy(scoped.filter((deal) => deal.type === 'project'), (deal) => deal.actualRevenue)
  const activeMrr = sumBy(scoped.filter((deal) => deal.mrr && !deal.churned), (deal) => deal.mrr)
  const capacity = Math.max(...scoped.map((deal) => deal.capacityHours ?? 0), 1)
  const soldHours = Math.max(...scoped.map((deal) => deal.soldHours ?? 0), 0)
  const occupancy = soldHours / capacity
  const churned = scoped.filter((deal) => deal.churned).length
  return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="Faturamento de projetos" value={formatCurrency(projectRevenue, true)} meta="projetos e setup realizados" change={0.14} description="Receita pontual reconhecida por entregas." tone="accent" /><KpiCard label="MRR recorrente" value={formatCurrency(activeMrr, true)} meta="sustentação ativa" change={0.08} description="Receita recorrente mensal; não inclui projeto pontual." /><KpiCard label="Ocupação de engenharia" value={formatPercent(occupancy)} meta={`${formatNumber(soldHours)}h de ${formatNumber(capacity)}h`} change={0.07} description="Capacidade comprometida versus capacidade mensal." /><KpiCard label="Churn de suporte" value={formatNumber(churned)} meta="contrato encerrado" change={-0.02} description="Cancelamentos na carteira de sustentação." /></div><div className="grid gap-6 xl:grid-cols-[1.15fr_1fr]"><Panel title="Composição da receita" subtitle="Projeto/Setup e recorrência têm tempos de reconhecimento distintos"><div className="grid h-72 place-items-center"><div className="grid w-full max-w-md grid-cols-2 gap-4"><div className="rounded-2xl border border-orange-100 bg-orange-50 p-5"><Layers3 className="text-orange-600" /><p className="mt-5 text-sm font-semibold text-orange-900">Projetos e setup</p><p className="mt-1 text-2xl font-bold text-orange-950">{formatCurrency(projectRevenue, true)}</p><p className="mt-2 text-xs text-orange-800">Reconhecido conforme entrega.</p></div><div className="rounded-2xl border border-sky-100 bg-sky-50 p-5"><CircleDollarSign className="text-sky-600" /><p className="mt-5 text-sm font-semibold text-sky-900">MRR e sustentação</p><p className="mt-1 text-2xl font-bold text-sky-950">{formatCurrency(activeMrr, true)}</p><p className="mt-2 text-xs text-sky-800">Previsibilidade mensal ativa.</p></div></div></div></Panel><Panel title="Capacidade versus vendas" subtitle="Contrato assinado não remove a restrição operacional"><div className="flex h-72 flex-col justify-center"><div className="mx-auto grid h-44 w-44 place-items-center rounded-full border-[14px] border-rose-100" style={{ borderTopColor: occupancy >= .9 ? '#f43f5e' : '#0ea5e9', borderRightColor: occupancy >= .9 ? '#f43f5e' : '#0ea5e9' }}><div className="text-center"><p className="text-3xl font-bold text-slate-900">{formatPercent(occupancy)}</p><p className="mt-1 text-xs font-medium text-slate-500">ocupação</p></div></div><div className="mt-6 flex items-start gap-2 rounded-xl bg-rose-50 p-3 text-sm leading-5 text-rose-900"><Users size={17} className="mt-0.5 shrink-0" /><span><strong>Risco de atraso:</strong> a capacidade atual deixa pouca margem para novos contratos sem replanejamento.</span></div></div></Panel></div></div>
}

export function CompanyDrilldown() {
  const { filters } = useFilters()
  const [selected, setSelected] = useState<CompanyId>('montseguro')
  const active = filters.companyId === 'all' ? selected : filters.companyId
  return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm text-slate-500">Leitura individual preservando a lógica do negócio</p><h2 className="mt-1 flex items-center gap-2 text-2xl font-bold tracking-tight text-slate-900"><Building2 className="text-sky-600" />{companies.find((company) => company.id === active)?.name}</h2></div><div className="section-tabs flex rounded-xl border p-1">{companies.map((company) => <button key={company.id} onClick={() => setSelected(company.id)} className={`rounded-lg px-3 py-2 text-sm font-semibold transition ${active === company.id ? 'tab-button--active text-white' : 'text-slate-500 hover:bg-white/70'}`}>{company.shortName}</button>)}</div></div>{active === 'montseguro' ? <MontseguroView /> : active === 'prop5' ? <Prop5View /> : <TechBraboView />}</div>
}
